### ISSUE TITLE
Refine build instructions

### ISSUE THREAD

**Issue by feuGeneA** [hbekel/bashrun2#4]
It would be nice if the README.md explained what dependencies are needed to build, and what packages can be installed to satisfy them.

I myself only encountered one missing build dependency, `X11/Xlib.h`, which I satisfied 
by installing the (Debian 9) package `libx11-dev`.

Also, for people who don't know, you should also mention the `make` and `make install` commands, and mention that it's likely you'll need to do `sudo make install`.

**Comment by hbekel** [comment]
Thanks, I've improved the README in Version 0.2.5 as suggested.
