### ISSUE TITLE
Terminal window pops up when starting telegram-desktop

### ISSUE THREAD

**Issue by scorpp** [hbekel/bashrun2#5]
Hi,

Having this problem since some of the version of telegram-desktop. It used to work well, just as it does for other GUI apps.

Is there a way to force bashrun not to open terminal window?

Tried adding following to config with no luck
```
     +rule run                                                         
       --match 'telegram-desktop'
```

My config [bashrun2.txt](https://github.com/hbekel/bashrun2/files/5687799/bashrun2.txt)
Flavor is ArchLinux

thanks

**Comment by hbekel** [comment]
Yes, I can confirm that telegram-desktop is one of the false positives. If no explicit rule is present for a program, Bashrun2 checks ldd output to run the program in terminal automatically if it finds some of the common terminal libraries. telegram-desktop is linked to libcursesw for some reason.

I have verified that the rule you supplied above does indeed overwrite this behavior and runs telegram-desktop without a terminal window. However, that rule is not present in the bashrun2 config you supplied, there's only one occurrence of the word "telegram" in a commented section.

**Comment by scorpp** [comment]
thank you @hbekel for quick response!

the section in config is commented out because it didn't work for me. i tried once again, uncommented it and the terminal window still appears.

then i remembered that bashrun has cache and headed to my `~/.cache/` and dropped whole `bashrun2` dir. and now everything broke up :-)
![2020-12-14_135420_865352659](https://user-images.githubusercontent.com/1970109/102078732-17882b00-3e14-11eb-8bb6-8dab070c1f16.png)

```
$ rm -rf ~/.cache/bashrun2/ && bashrun2 
install: creating directory '/home/user/.cache/bashrun2'
/home/user/.cache/bashrun2/config.bash: line 7: [1]=: command not found
/home/user/.cache/bashrun2/config.bash: line 8: [1]=: command not found
/home/user/.cache/bashrun2/template.bash: line 7: [1]=-name %n: command not found
/home/user/.cache/bashrun2/template.bash: line 8: [1]=: command not found
/home/user/.cache/bashrun2/terminal.bash: line 7: [1]=: command not found
/home/user/.cache/bashrun2/terminal.bash: line 8: [1]=: command not found
/home/user/.cache/bashrun2/mode.bash: line 7: [1]=xterm: command not found
/home/user/.cache/bashrun2/mode.bash: line 8: [1]=: command not found
/home/user/.cache/bashrun2/template.bash: line 7: [1]=-name %n: command not found
/home/user/.cache/bashrun2/template.bash: line 8: [1]=: command not found
/home/user/.cache/bashrun2/terminal.bash: line 7: [1]=: command not found
/home/user/.cache/bashrun2/terminal.bash: line 8: [1]=: command not found
```

now i've removed my configs and only defaults are left in `/etc/xdg/bashrun2`
first lines of `~/.cache/bashrun2/config.bash` look like this:
```
_bashrun_configs=()                                                                                                                                                                                                 
_bashrun_configs_keys=(type names)                                                                                                                                                                                  
_bashrun_configs_defaults=[0]="" [1]=""                                                                                                                                                                             
_bashrun_configs_types=[0]="" [1]=""                                                                                                                                                                                
_bashrun_configs_width=${#_bashrun_configs_keys[@]}                                                                                                                                                                 
_bashrun_configs_position=0                                                                                                                                                                                         
_bashrun_configs_size=0                                                                                                                                                                                             
_bashrun_configs_modified=0                                                                                                                                                                                         
                                                                                                                                                                                                                    
_bashrun_configs_have_interface=0                                                                                                                                                                                   
_bashrun_configs_interface_methods=''                                                                                                                                                                               
_bashrun_configs_interface_options=''    
```

bashrun2 is 0.2.3
bash is 5.1.0(1)
xterm is 362

please advise how to get it back working

**Comment by hbekel** [comment]
Please update to 0.2.4, where these parsing errors have been fixed.

A source package can be found at http://henning-liebenau.de/download/bashrun2/bashrun2-0.2.4.tar.gz

You may want to use the AUR package https://aur.archlinux.org/packages/bashrun2/. It should be enough to bump the version and update the md5sum.

**Comment by scorpp** [comment]
fantastic! all issue solved, bashrun works again, telegram behaves!

i went to releases, and surprised, why haven't a received a 0.2.4 via AUR? then i went to AUR by your link. and looked at the maintainer. and it was me! a-ha, that's why! :-D

thank you very much for the software and help!

**Comment by hbekel** [comment]
Ok, glad it works now, and thank you for maintaining the AUR package :)
